apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-argo
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-argo
    spec:
      containers:
      - name: nginx-con
        image: 132464628555.dkr.ecr.ap-northeast-2.amazonaws.com/web-argo:1
